server:
  port: 9090

spring:
  redis:
    database: 1
    host: 120.55.80.133
    port: 6380
    password: 3039@Hyd123G,,,
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s


